/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 bear.glb --transform
*/

import React, { useLayoutEffect, useMemo, useRef } from "react";
import { useAnimations, useGLTF, useScroll } from "@react-three/drei";
import { folder, useControls } from "leva";
import { useFrame } from "react-three-fiber";
import { gsap } from "gsap";
import { useEffect } from "react";

export function Model(props) {
  const group = useRef();
  const scroll = useScroll();
  const tl = useRef();

  const { nodes, materials, animations } = useGLTF(
    "/models/bear4/bear-transformed.glb"
  );
  const { actions, names } = useAnimations(animations, group);

  // console.log(names);
  useEffect(() => {
    actions[names[0]].play();
  }, []);

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline({
      defaults: { duration: 2, ease: "power1.inOut" },
    });
    tl.current
      .set(group.current?.scale, { x: 1.4, y: 1.4, z: 1.4 })
      .set(group.current?.position, { x: 0, y: -11.48, z: -7.5 })
      .set(group.current?.rotation, { y: 0, x: 0 })
      .to(group.current?.rotation, { y: -0.35 }, 0)

      .to(group.current.scale, { x: 1.4, y: 1.4, z: 1.4 }, 0)
      // .to(group.current?.rotation, {"y":0.37}, 0)

      .to(group.current?.position, { x: 2.88, y: -11.48, z: -6 }, 5)
      .to(group.current?.position, { z: -6 }, 6)
      .to(group.current?.rotation, { x: 0, y: 0.37, z: 0 }, 6)
      .to(group.current?.rotation, { x: -0.17 }, 7)
      .to(group.current?.rotation, { x: 0, y: 1 }, 10)
      .to(group.current?.position, { x: 0, y: -5, z: -7 }, 10)

      .to(group.current?.rotation, { y: 6.35, x: 0 }, 12)
      .to(group.current?.position, { x: 0, y: -7.17, z: -9 }, 13)

      .to(group.current?.rotation, { x: 0, y: 6.35 }, 15)
      .to(group.current?.position, { x: 0, y: -7.17, z: -10 }, 16);
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="BearRig002" position={[0.033, -0.132, 3.113]}>
          <primitive object={nodes.spine} />
          <primitive object={nodes.neutral_bone} />
          <primitive object={nodes.neutral_bone_1} />
          <skinnedMesh
            name="Bear"
            geometry={nodes.Bear.geometry}
            material={materials["Bear black"]}
            skeleton={nodes.Bear.skeleton}
          />
          <group name="Mask">
            <skinnedMesh
              name="Object023_21_-_Default_0001"
              geometry={nodes["Object023_21_-_Default_0001"].geometry}
              material={materials["21_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_1"
              geometry={nodes["Object023_21_-_Default_0001_1"].geometry}
              material={materials["03_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_1"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_2"
              geometry={nodes["Object023_21_-_Default_0001_2"].geometry}
              material={materials["15_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_2"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_3"
              geometry={nodes["Object023_21_-_Default_0001_3"].geometry}
              material={materials["09_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_3"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_4"
              geometry={nodes["Object023_21_-_Default_0001_4"].geometry}
              material={materials["11_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_4"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_5"
              geometry={nodes["Object023_21_-_Default_0001_5"].geometry}
              material={materials["13_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_5"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_6"
              geometry={nodes["Object023_21_-_Default_0001_6"].geometry}
              material={materials["19_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_6"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_7"
              geometry={nodes["Object023_21_-_Default_0001_7"].geometry}
              material={materials["07_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_7"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_8"
              geometry={nodes["Object023_21_-_Default_0001_8"].geometry}
              material={materials["10_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_8"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_9"
              geometry={nodes["Object023_21_-_Default_0001_9"].geometry}
              material={materials["08_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_9"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_10"
              geometry={nodes["Object023_21_-_Default_0001_10"].geometry}
              material={materials["14_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_10"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_11"
              geometry={nodes["Object023_21_-_Default_0001_11"].geometry}
              material={materials["02_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_11"].skeleton}
            />
            <skinnedMesh
              name="Object023_21_-_Default_0001_12"
              geometry={nodes["Object023_21_-_Default_0001_12"].geometry}
              material={materials["20_-_Default"]}
              skeleton={nodes["Object023_21_-_Default_0001_12"].skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/bear4/bear-transformed.glb");
