/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 bear1.glb --transform
*/

import React, { useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { folder, useControls } from "leva";

export function Model(props) {
  const { scale } = useControls("Scale", {
    transform: folder({
      scale: {
        value: 3,
        min: 0.4,
        max: 16,
        step: 0.1,
      },
    }),
  });
  const po = useMemo(() => {
    return {
      x: { value: 0.01, min: -16, max: 32, step: 0.01 },
      y: { value: 0.01, min: -16, max: 32, step: 0.01 },
      z: { value: 0.01, min: -16, max: 32, step: 0.01 },
    };
  }, []);
  const rot = useMemo(() => {
    return {
      x: { value: 0.01, min: -16, max: 32, step: 0.01 },
      y: { value: 0.01, min: -16, max: 32, step: 0.01 },
      z: { value: 0.01, min: -16, max: 32, step: 0.01 },
    };
  }, []);
  const posi = useControls("position", po);
  const rotate = useControls("rotation", rot);

  const { nodes, materials } = useGLTF("/models/bear1/bear1-transformed.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={scale}
      // position={position}
      position={[posi.x, posi.y, posi.z]}
      rotation={[rotate.x, rotate.y, rotate.z]}
    >
      <mesh
        geometry={nodes.Body001.geometry}
        material={materials["Sci fi wall material"]}
        position={[-0.08, 4.37, 0.25]}
        scale={[0.65, 0.63, 0.55]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Sci fi wall material"]}
        position={[-0.03, 4.67, 1.5]}
        rotation={[1.56, -Math.PI / 4, 0]}
        scale={[0.15, 0.01, 0.15]}
      />
      <group
        position={[0.45, 4.07, -1.79]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.02, 0.04, 0.01]}
      >
        <mesh
          geometry={nodes.Cube077.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cube077_1.geometry}
          material={materials["Procedural Metal Plates"]}
        />
        <mesh
          geometry={nodes.Cube077_2.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube077_3.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Cube077_4.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Cube077_5.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Cube077_6.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <mesh
        geometry={nodes.Head.geometry}
        material={materials["Sci fi wall material"]}
        position={[-0.07, 7.04, 0.33]}
        rotation={[0, 0, -Math.PI]}
        scale={[1.72, 1.5, 1.47]}
      />
      <mesh
        geometry={nodes.Left_arm001.geometry}
        material={materials["Sci fi wall material"]}
        position={[1.33, 4.92, 0.29]}
        rotation={[-Math.PI, 0, -0.32]}
        scale={[-0.29, -0.33, -0.4]}
      />
      <mesh
        geometry={nodes.LeftEar.geometry}
        material={materials["Sci fi wall material"]}
        position={[-0.91, 7.76, 0.39]}
        rotation={[0.09, 0.03, 0.52]}
        scale={[0.82, 0.86, 0.75]}
      />
      <mesh
        geometry={nodes.LegLoop.geometry}
        material={materials["Sci fi wall material"]}
        position={[-0.83, 1.18, 0.28]}
        rotation={[0, 0, -0.07]}
        scale={[0.37, 0.49, 0.37]}
      />
      <mesh
        geometry={nodes.Legs.geometry}
        material={materials["Sci fi wall material"]}
        position={[-0.03, 4.6, 0.26]}
        scale={[0.86, 1.05, 0.93]}
      />
      <mesh
        geometry={nodes.Mouth.geometry}
        material={materials["Sci fi wall material"]}
        position={[-0.08, 6.61, 1.16]}
        rotation={[0, 0, -Math.PI]}
        scale={[1.14, 1, 0.86]}
      />
      <mesh
        geometry={nodes.Nose.geometry}
        material={materials["Sci fi wall material"]}
        position={[-0.08, 6.84, 1.8]}
        scale={[0.29, 0.16, 0.36]}
      />
      <mesh
        geometry={nodes.NoseLIne.geometry}
        material={materials["Sci fi wall material"]}
        position={[-0.09, 6.5, 1.72]}
        scale={[0.1, 0.52, 0.37]}
      />
      <mesh
        geometry={nodes.Right_arm001.geometry}
        material={materials["Sci fi wall material"]}
        position={[-1.53, 4.91, 0.2]}
        rotation={[0, 0, -0.28]}
        scale={[0.29, 0.33, 0.4]}
      />
      <mesh
        geometry={nodes.RightEar.geometry}
        material={materials["Sci fi wall material"]}
        position={[0.64, 7.83, 0.31]}
        rotation={[0.09, 0.05, -1.03]}
        scale={[0.82, 0.86, 0.75]}
      />
    </group>
  );
}

useGLTF.preload("/models/bear1/bear1-transformed.glb");
