/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 bear.glb --transform
*/

import React, { useLayoutEffect, useMemo, useRef } from "react";
import { useAnimations, useGLTF, useScroll } from "@react-three/drei";
import { folder, useControls } from "leva";
import { useFrame } from "react-three-fiber";
import { gsap } from "gsap";
import { useEffect } from "react";

export function Model(props) {
  const group = useRef();
  const scroll = useScroll();
  const tl = useRef();

  const { nodes, materials, animations } = useGLTF(
    "/models/bear4/bear-transformed.glb"
  );

  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]]?.play();
  }, []);

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline({
      defaults: { duration: 2, ease: "power1.inOut" },
    });
    tl.current
      .set(group.current?.scale, { x: 1.4, y: 1.4, z: 1.4 })
      .set(group.current?.position, { x: 0, y: -11.48, z: -6 })
      .set(group.current?.rotation, { y: 0, x: 0 })
      .to(group.current?.rotation, { y: -0.35 }, 0)

      .to(group.current?.scale, { x: 1.4, y: 1.4, z: 1.4 }, 0)
      // .to(group.current?.rotation, {"y":0.37}, 0)

      .to(group.current?.position, { x: 2.88, y: -11.48, z: -6 }, 5)
      .to(group.current?.position, { z: -6 }, 6)
      .to(group.current?.rotation, { x: 0, y: 0.37, z: 0 }, 6)
      .to(group.current?.rotation, { x: -0.17 }, 7)
      .to(group.current?.rotation, { x: 0, y: 1 }, 10)
      .to(group.current?.position, { x: 0, y: -5, z: -7 }, 10)

      .to(group.current?.rotation, { y: 6.35, x: 0 }, 12)
      .to(group.current?.position, { x: 0, y: -7.17, z: -9 }, 13)

      .to(group.current?.rotation, { x: 0, y: 6.35 }, 15)
      .to(group.current?.position, { x: 0, y: -7.17, z: -10 }, 16);
  }, []);

  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  );
}

useGLTF.preload("/models/bear4/bear-transformed.glb");
