/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 line.gltf --transform
*/

import { useGLTF, useScroll } from "@react-three/drei";
import { gsap } from "gsap";
import { useLayoutEffect } from "react";
import { useRef } from "react";
import { useFrame, useThree } from "react-three-fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/line/line-transformed.glb");

  const scroll = useScroll();
  const tl = useRef();
  const meshRef = useRef();

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline({});
    tl.current
      .set(meshRef.current?.position, { x: 0.2, y: -0.5, z: -3 }, 0)
      .set(meshRef.current?.scale, { x: 4, y: 0.3, z: 0.1 }, 0)
      .to(meshRef.current?.position, { y: 15 }, "1%");
  }, []);
  return (
    <group {...props} dispose={null} ref={meshRef}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        scale={[20.636, 0.128, 0.152]}
      />
    </group>
  );
}

useGLTF.preload("/models/line/line-transformed.glb");
