/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 logo.glb --transform
*/

import { useGLTF, useScroll } from "@react-three/drei";
import { gsap } from "gsap";
import { useLayoutEffect } from "react";
import { useRef } from "react";
import { useFrame, useThree } from "react-three-fiber";

export function Model(props) {
  const scroll = useScroll();
  const tl = useRef();
  const meshRef = useRef();

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline({});
    tl.current
      .set(meshRef.current?.position, { x: 0.2, y: 0, z: -3 }, 0)
      .set(meshRef.current?.scale, { x: 4, y: 4, z: 4 }, 0)
      .to(meshRef.current?.position, { y: 15 }, "1%");
  }, []);

  const { nodes, materials } = useGLTF("/models/logo/logo-transformed.glb");
  return (
    <group {...props} dispose={null} ref={meshRef}>
      <mesh
        geometry={nodes.Body002.geometry}
        material={materials["Procedural Abstract Sci-Fi Tech 2.0"]}
        position={[0.245, 0.379, -0.782]}
        scale={[0.245, 0.234, 0.37]}
      />
      <mesh
        geometry={nodes.Body004.geometry}
        material={materials["Violet Glass"]}
        position={[0.245, 0.379, -0.778]}
        scale={[0.245, 0.234, 0.37]}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials["Sci-Fi Emission"]}
        position={[-0.009, 0.368, 0.096]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.915, 0.559, 0.915]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["SciFi Plastic 01"]}
        position={[-0.009, 0.379, 0.096]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.915, 1.273, 0.915]}
      />
    </group>
  );
}

useGLTF.preload("/models/logo/logo-transformed.glb");
