/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bear.gltf --transform
*/

import React, { useLayoutEffect, useMemo, useRef } from "react";
import { useAnimations, useGLTF, useScroll } from "@react-three/drei";
import { folder, useControls } from "leva";
import { useFrame } from "react-three-fiber";
import { gsap } from "gsap";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/new/bear-transformed.glb");
  const scroll = useScroll();
  const bear = useRef();
  const tl = useRef();

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline({
      defaults: { duration: 2, ease: "power1.inOut" },
    });
    tl.current
      .set(bear.current?.scale, { x: 1.4, y: 1.4, z: 1.4 })
      .set(bear.current?.position, { x: 0, y: -11.48, z: -1.11 })
      .set(bear.current?.rotation, { y: 0 })
      .to(bear.current?.rotation, { y: -0.35 }, 0)

      .to(bear.current.scale, { x: 1.4, y: 1.4, z: 1.4 }, 0)
      // .to(bear.current?.rotation, {"y":0.37}, 0)

      .to(bear.current?.position, { x: -2, y: -11.48, z: -1.11 }, 3)
      .to(bear.current?.scale, { x: 1.5, y: 1.5, z: 1.5 }, 3)
      .to(bear.current?.rotation, { x: 0, y: 0, z: 0 }, 3)
      .to(bear.current?.position, { x: 2.88, y: -11.48, z: -1.11 }, 5)
      .to(bear.current?.position, { z: -3 }, 6)
      .to(bear.current?.rotation, { x: 0, y: 0.37, z: 0 }, 6)
      .to(bear.current?.rotation, { x: -0.17 }, 7)
      .to(bear.current?.rotation, { x: 0.1, y: 3 }, 10)
      .to(bear.current?.position, { x: 3.03, y: -11, z: -3 }, 10)

      .to(bear.current?.rotation, { y: 6.35, x: 0 }, 12)
      .to(bear.current?.position, { x: 0, y: -7.17, z: -5.01 }, 13)

      .to(bear.current?.rotation, { x: 0, y: 6.35 }, 15)
      .to(bear.current?.position, { x: 0, y: -7.17, z: -7.53 }, 16);
  }, []);

  return (
    <group {...props} dispose={null} ref={bear}>
      <mesh
        geometry={nodes.Bear014.geometry}
        material={materials.Bear}
        position={[0, 4.408, 0.132]}
      />
      <group position={[0, 5.117, 1.333]}>
        <mesh
          geometry={nodes.Mesh018.geometry}
          material={materials["Yellow glow"]}
        />
        <mesh
          geometry={nodes.Mesh018_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/new/bear-transformed.glb");
