const ShopItemData = [
  {
    id: 1,
    video: "",
    name: "Essential T-Shirt - Tiger Style",
    price: 0.00245,
    cmp: 245.674,
    colorName: "Tiger Style/Orange",
    colorNumber: 1,
    Rarity: "common",
    Remaining: 3,
    TotalNumber: 40,
    discount: 20,
  },
  {
    id: 2,
    video: "",
    name: "Essential T-Shirt - Tiger Style",
    price: 0.00245,
    cmp: 245.674,
    colorName: "TElephant Style/Orange",
    colorNumber: 3,
    Rarity: "common",
    Remaining: 3,
    TotalNumber: 40,
    discount: 27,
  },
  //   {
  //     id: 3,
  //     image: "",
  //     name: "Essentialing T-Shirt - Tiger Style",
  //     price: 0.00245,
  //     cmp: 245.674,
  //     colorName: "Tiger Style/Red",
  //     colorNumber: 1,
  //     Rarity: "Rare",
  //     Remaining: 17,
  //     TotalNumber: 40,
  //     discount: 21,
  //   },
  //   {
  //     id: 4,
  //     image: "",
  //     name: "Essential T-Shirt - Tiger Style",
  //     price: 0.00245,
  //     cmp: 245.674,
  //     colorNumber: 1,
  //     Rarity: "common",
  //     Remaining: 3,
  //     TotalNumber: 40,
  //     discount: 22,
  //   },
  //   {
  //     id: 5,
  //     image: "",
  //     name: "Essential T-Shirt - Tiger Style",
  //     price: 0.00245,
  //     cmp: 245.674,
  //     colorNumber: 1,
  //     Rarity: "common",
  //     Remaining: 3,
  //     TotalNumber: 40,
  //     discount: 10,
  //   },
  //   {
  //     id: 6,
  //     image: "",
  //     name: "Essential T-Shirt - Tiger Style",
  //     price: 0.00245,
  //     cmp: 245.674,
  //     colorNumber: 1,
  //     Rarity: "common",
  //     Remaining: 3,
  //     TotalNumber: 40,
  //     discount: 20,
  //   },
];

export default ShopItemData;
